// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// prisma generate runs during postinstall (e.g. on Vercel build) and does NOT
// need a real database URL — it only reads the schema to generate the client.
// env() throws PrismaConfigEnvError if the variable is missing, so we provide a
// placeholder that satisfies the config loader during generate. At runtime, the
// app reads DATABASE_URL directly in src/lib/prisma.ts and will fail fast if it
// is not set.
const databaseUrl = (() => {
  try {
    return env("DATABASE_URL");
  } catch {
    // generate-only path — placeholder URL, never used for real connections
    return "postgresql://placeholder:placeholder@localhost:5432/postgres";
  }
})();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
